services:

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: metadata_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    container_name: mlflow
    ports:
      - "5001:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password123
    command: >
      mlflow server
      --backend-store-uri postgresql://admin:admin123@postgres:5432/metadata_db
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0
      --port 5000
    depends_on:
      - postgres
      - minio

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  prefect:
    image: prefecthq/prefect:2-python3.11
    container_name: prefect
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0
    volumes:
      - prefect_data:/root/.prefect

volumes:
  minio_data:
  postgres_data:
  prefect_data: